Models/Hobby.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BeltExam.Models
{
    public class Hobby
    {
        [Key]
        public int HobbyId { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime UpdatedAt { get; set; } = DateTime.Now;
        public int UserId { get; set; }
        public User Creator { get; set;}
        public List<UserHobby> AllUsers { get; set; }
        
    }
}

Controllers/HobbyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using BeltExam.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace BeltExam.Controllers
{
    public class HobbyController : Controller
    {
        private MyContext _context;

        public HobbyController(MyContext context)
        {
            _context = context;
        }

        [HttpGet("Hobby/New")]
        public ActionResult AddHobby()
        {
            if(HttpContext.Session.GetInt32("uid") != null)
                return View();
            return Redirect("/");
        }
        [HttpPost("hobby/create")]
        public IActionResult CreateHobby(Hobby newHobby)
        {
            if(ModelState.IsValid)
            {
                if(!_context.Hobbies.Any(h => h.Name == newHobby.Name))
                {
                    int uid = (int)HttpContext.Session.GetInt32("uid");
                    newHobby.UserId = uid;
                    _context.Hobbies.Add(newHobby);
                    _context.SaveChanges();
                    
                    UserHobby AddUserToHobby = new UserHobby();
                    AddUserToHobby.HobbyId = newHobby.HobbyId;
                    AddUserToHobby.UserId = uid;
                    _context.UserHobbies.Add(AddUserToHobby);
                    _context.SaveChanges();
                    return Redirect("/Hobby");
                }

                ModelState.AddModelError("Name", "Hobby is already Added!");
                return View("AddHobby");
            }
            return View("AddHobby");
        }

        [HttpGet("Hobby/{hobId}")]
        public ViewResult HobbyDetail(int hobId)
        {
            Hobby thisHobby = _context.Hobbies
            .Include(h => h.AllUsers)
            .ThenInclude(uh => uh.UserOnHobby)
            .FirstOrDefault( h => h.HobbyId == hobId);
            return View(thisHobby);
        }

        [HttpGet("addHobbyToUser/{hobId}")]

        public ActionResult AddHobbyToUser( int hobId)
        {
            int uid = (int)HttpContext.Session.GetInt32("uid");
            UserHobby newHobby = new UserHobby();
            newHobby.HobbyId = hobId;
            newHobby.UserId = uid;
            _context.UserHobbies.Add(newHobby);
            _context.SaveChanges();

            return Redirect($"/Hobby/{hobId}");
        }

        [HttpGet("Hobby/Edit/{hobId}")]

        public ViewResult EditHobby(int hobId)
        {
            Hobby thisHobby = _context.Hobbies.FirstOrDefault( h => h.HobbyId == hobId);

            return View("EditHobby", thisHobby);
        }

        [HttpPost("Hobby/processedit/{hobId}")]
        public ActionResult ProcessEditHobby(int hobId, Hobby editedHobby)
        {
            Hobby thisHobby = _context.Hobbies.FirstOrDefault( h => h.HobbyId == hobId);
            if(ModelState.IsValid)
            {
                thisHobby.Name = editedHobby.Name;
                thisHobby.Description = editedHobby.Description;
                thisHobby.UpdatedAt = DateTime.Now;
                _context.SaveChanges();
                return Redirect($"/Hobby/{thisHobby.HobbyId}");
            }

            return View("EditHobby", thisHobby);
        }
    }
}

Views/Hobby/AddHobby.cshtml
@model Hobby
@{
    ViewData["Tilte"] = "Add Hobby";
}

<div class="flx">
    
        <h1>Create a Hobby</h1> 
</div>

<div class="addHob">
    <form asp-action="CreateHobby" asp-controller="Hobby" class="form-group">
        <div class="form-group">
            <label asp-for="Name"></label><br>
            <input asp-for="Name"><br>
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description"></label><br>
            <input asp-for="Description" ><br>
            <span class="text-danger" asp-validation-for="Description"></span>
        </div>
        <input type="submit" value="Create" class="btn btn-dark">
    </form>
</div>

Views/Hobby/EditHobby.cshtml
@model Hobby
@{
    ViewData["Tilte"] = "Edit Hobby";
}

<div class="flx">
    
        <h1>Edit a Hobby</h1>  
</div>

<div class="editHob">
    <form asp-action="ProcessEditHobby" asp-controller="Hobby" class="form-group">
        <div class="form-group">
            <label asp-for="Name"></label><br>
            <input asp-for="Name"><br>
            <span class="text-danger" asp-validation-for="Name"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description"></label><br>
            <input asp-for="Description" ><br>
            <span class="text-danger" asp-validation-for="Description"></span>
        </div>
        <input type="submit" value="Update" class="btn btn-dark">
    </form>
</div>

Views/Hobby/HobbyDetail.cshtml
@model Hobby
@{
    ViewData["Tilte"] = "Hobby Details";
}
@{
    int UserID = (int)Context.Session.GetInt32("uid");
}

<h1>@Model.Name</h1>
<div class="des">
    <p>Description: @Model.Description</p>
</div>

<div class="flx">
    <div class="left">
        <h5>@Model.Name Enthusiasts:</h5>
        <div class="lis">
            @{
                foreach(UserHobby uh in Model.AllUsers)
                {
                    <ul>
                        <li>@uh.UserOnHobby.FirstName</li>
                    </ul>
                }
            }
        </div>
    </div>
    <div class="right">
        @{
            if(!@Model.AllUsers.Any(h => h.UserOnHobby.UserId == UserID))
            {
                <p>Become an Enthusiast!</p>
                <button class="btn btn-dark"><a href="/addHobbyToUser/@Model.HobbyId">Add to Hobbies</a></button>
            }
        }
        <br>
        <br>
        <button class="btn btn-dark"><a href="/Hobby">Back to All Hobbies</a></button>
    </div>
    <div class="last">
        <br>
        <br>
        <button class="btn btn-dark"><a href="/Hobby/Edit/@Model.HobbyId">Edit Hobby</a></button>
    </div>
</div>